"""Tier 1 Wikipedia source lists.

Each source is a page whose content links to concept articles we want to ingest.
`content_selector` is a CSS selector for the region of the page containing the
list entries — we only extract <li> items inside that region so we skip nav,
see-also, and references sections. Defaults to ``.mw-parser-output`` (whole
article body), with post-filters in ``extract.py`` removing obvious non-entries.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Source:
    # Wikipedia page title (with underscores or spaces; MediaWiki accepts both)
    page: str
    # Short stable id used as `source_list` in the DB
    key: str
    # Human-readable name
    name: str
    # Which `form` to default to when the concept came from this list
    default_form: str
    # Skip any list item whose link title starts with these strings
    skip_prefixes: tuple[str, ...] = field(default_factory=tuple)
    # Section IDs to exclude (Wikipedia anchor ids, lowercase with underscores)
    exclude_sections: tuple[str, ...] = (
        "See_also",
        "References",
        "Notes",
        "Further_reading",
        "External_links",
        "Bibliography",
        "Sources",
    )


SOURCES: list[Source] = [
    Source(
        page="List of cognitive biases",
        key="cognitive_biases",
        name="Cognitive biases",
        default_form="bias",
    ),
    Source(
        page="List of fallacies",
        key="fallacies",
        name="Fallacies",
        default_form="fallacy",
    ),
    Source(
        page="List of paradoxes",
        key="paradoxes",
        name="Paradoxes",
        default_form="paradox",
    ),
    Source(
        page="List of thought experiments",
        key="thought_experiments",
        name="Thought experiments",
        default_form="thought_experiment",
    ),
    Source(
        page="List of effects",
        key="effects",
        name="Named effects",
        default_form="effect",
    ),
    Source(
        page="List of eponymous laws",
        key="eponymous_laws",
        name="Eponymous laws",
        default_form="law",
    ),
    Source(
        page="List of narrative techniques",
        key="narrative_techniques",
        name="Narrative techniques",
        default_form="device",
    ),
    Source(
        page="List of stock characters",
        key="stock_characters",
        name="Stock characters",
        default_form="archetype",
    ),
    Source(
        page="List of software anti-patterns",
        key="anti_patterns",
        name="Software anti-patterns",
        default_form="anti_pattern",
    ),
    Source(
        page="List of games in game theory",
        key="game_theory_games",
        name="Game theory games",
        default_form="game",
    ),
    Source(
        page="Glossary of rhetorical terms",
        key="rhetorical_terms",
        name="Rhetorical terms",
        default_form="device",
    ),
]


@dataclass
class ManualSource:
    """A curated list of Wikipedia article titles, used when no list page works."""

    key: str
    name: str
    default_form: str
    titles: tuple[str, ...]


MANUAL_SOURCES: list[ManualSource] = [
    ManualSource(
        key="buddhism",
        name="Buddhist concepts",
        default_form="concept",
        titles=(
            "Four Noble Truths",
            "Noble Eightfold Path",
            "Three marks of existence",
            "Anicca",
            "Dukkha",
            "Anattā",
            "Skandha",
            "Pratītyasamutpāda",
            "Śūnyatā",
            "Tathātā",
            "Tathāgatagarbha",
            "Bodhicitta",
            "Bodhisattva",
            "Pāramitā",
            "Three poisons",
            "Karma in Buddhism",
            "Saṃsāra",
            "Nirvana (Buddhism)",
            "Mu (negative)",
            "Satori",
            "Kenshō",
            "Kōan",
            "Shoshin",
            "Mushin (mental state)",
            "Zazen",
            "Mettā",
            "Sati (Buddhism)",
            "Upāya",
            "Two truths doctrine",
            "Middle Way",
            "Twelve Nidānas",
            "Karuṇā",
            "Muditā",
            "Upekkhā",
            "Brahmavihara",
            "Three Jewels",
            "Five precepts",
            "Bodhi",
            "Buddha-nature",
            "Trikaya",
            "Arhat",
            "Pratyekabuddha",
            "Stream-enterer",
            "Five hindrances",
            "Seven Factors of Awakening",
            "Bhavana",
            "Vipassanā",
            "Samatha",
            "Pure Land Buddhism",
            "Vajrayana",
            "Mahayana",
            "Theravada",
            "Zen",
            "Mindfulness",
            "Buddhahood",
            "Right view",
            "Buddhist ethics",
            "Buddhist meditation",
            "Eight Consciousnesses",
        ),
    ),
    ManualSource(
        key="hindu_vedic",
        name="Hindu and Vedic concepts",
        default_form="concept",
        titles=(
            "Dharma",
            "Karma",
            "Moksha",
            "Saṃsāra",
            "Ātman (Hinduism)",
            "Brahman",
            "Maya (religion)",
            "Lila (Hinduism)",
            "Guṇa",
            "Ahimsa",
            "Tat Tvam Asi",
            "Neti neti",
            "Ishvara",
            "Avidyā (Hinduism)",
            "Bhakti",
            "Jnana",
            "Purusha",
            "Prakriti",
            "Kundalini",
            "Chakra",
            "Samkhya",
            "Yoga (philosophy)",
            "Vairagya",
            "Satcitananda",
            "Trimurti",
            "Shakti",
            "Pranayama",
            "Mantra",
            "Yantra",
            "Tantra",
            "Yamas",
            "Niyama",
            "Kosha",
            "Asana",
            "Samadhi",
            "Pratyahara",
            "Dharana",
            "Kaivalya",
            "Kleshas",
            "Saṃskāra",
            "Vāsanā",
            "Advaita Vedanta",
            "Dvaita Vedanta",
            "Vishishtadvaita",
            "Bhakti yoga",
            "Karma yoga",
            "Jnana yoga",
            "Raja yoga",
            "Bhagavad Gita",
            "Purushartha",
            "Ashrama (stage)",
            "Varna (Hinduism)",
            "Rita",
        ),
    ),
    ManualSource(
        key="taoism",
        name="Taoist concepts",
        default_form="concept",
        titles=(
            "Tao",
            "Wu wei",
            "Ziran",
            "De (Chinese)",
            "Pu (Taoism)",
            "Yin and yang",
            "Qi",
            "Three Treasures (Taoism)",
            "Tao Te Ching",
            "Bagua",
            "Wu Xing",
            "I Ching",
            "Hexagram (I Ching)",
            "Tian",
            "Neidan",
            "Xian (Taoism)",
            "Three Pure Ones",
            "Eight Immortals",
            "Fangshi",
            "Zhuangzi (book)",
            "Butterfly dream",
        ),
    ),
    ManualSource(
        key="confucianism",
        name="Confucian concepts",
        default_form="concept",
        titles=(
            "Ren (Confucianism)",
            "Li (Confucianism)",
            "Yi (Confucianism)",
            "Xin (heart-mind)",
            "Junzi",
            "Filial piety",
            "Mandate of Heaven",
            "Rectification of names",
            "Three Obediences and Four Virtues",
            "Five Classics",
            "Four Books",
            "Great Learning",
            "Doctrine of the Mean",
            "Analects",
            "Mencius (book)",
            "Neo-Confucianism",
            "Eight Virtues",
        ),
    ),
    ManualSource(
        key="stoicism",
        name="Stoic concepts",
        default_form="concept",
        titles=(
            "Eudaimonia",
            "Apatheia",
            "Ataraxia",
            "Logos",
            "Amor fati",
            "Memento mori",
            "Negative visualization",
            "Cosmopolitanism",
            "Virtue ethics",
            "Stoic categories",
            "Cardinal virtues",
            "Pneuma",
            "Oikeiosis",
            "Prohairesis",
            "Stoic passions",
            "Stoic physics",
            "Stoic logic",
            "Enchiridion of Epictetus",
            "Meditations",
            "Cynicism (philosophy)",
        ),
    ),
    ManualSource(
        key="greek_philosophy",
        name="Greek philosophical concepts",
        default_form="concept",
        titles=(
            "Sophrosyne",
            "Phronesis",
            "Akrasia",
            "Hubris",
            "Kairos",
            "Arete",
            "Telos",
            "Aporia",
            "Apophasis",
            "Epicureanism",
            "Hedonism",
            "Theory of forms",
            "Allegory of the cave",
            "Socratic method",
            "Maieutics",
            "Pathos",
            "Ethos",
            "Eros (concept)",
            "Agape",
            "Philia",
            "Storge",
            "Nous",
            "Doxa",
            "Episteme",
            "Techne",
            "Mimesis",
            "Catharsis",
            "Anamnesis (philosophy)",
            "Aletheia",
            "Metanoia (theology)",
            "Anagnorisis",
            "Peripeteia",
            "Hamartia",
            "Logos",
            "Mythos",
            "Ananke (mythology)",
            "Moira",
            "Daimon",
            "Hylomorphism",
            "Four causes",
            "Golden mean (philosophy)",
            "Megalopsychia",
            "Ate (mythology)",
            "Nemesis (mythology)",
        ),
    ),
    ManualSource(
        key="japanese_aesthetics",
        name="Japanese aesthetics",
        default_form="concept",
        titles=(
            "Wabi-sabi",
            "Mono no aware",
            "Yūgen",
            "Iki (aesthetics)",
            "Mujō",
            "Ma (negative space)",
            "Shibui",
            "Kintsugi",
            "Ikigai",
            "Mottainai",
            "Komorebi",
            "Honne and tatemae",
            "Bushido",
            "Hara hachi bun me",
            "Kaizen",
            "Nemawashi",
            "Genchi Genbutsu",
            "Amae",
            "Yutori education",
            "Tsundoku",
            "Hanami",
            "Datsuzoku",
            "Yamato-damashii",
            "Giri (Japanese)",
            "Wa (Japanese culture)",
            "Omoiyari",
            "Gaman (term)",
            "Ganbaru",
            "Karoshi",
            "Hikikomori",
            "Mushin (mental state)",
        ),
    ),
    ManualSource(
        key="sufism",
        name="Sufi concepts",
        default_form="concept",
        titles=(
            "Fana (Sufism)",
            "Baqaa",
            "Tawhid",
            "Ihsan",
            "Dhikr",
            "Maqam (Sufism)",
            "Hal (Sufism)",
            "Nafs",
            "Murid",
            "Sohbet",
            "Wahdat al-wujud",
            "Al-Insān al-Kāmil",
            "Tariqa",
            "Sema",
            "Murshid",
            "Qalb",
            "Khalwa",
            "Adab (Islam)",
            "Sabr",
            "Tawakkul",
            "Shukr",
            "Taqwa",
            "Niyyah",
            "Fitra",
        ),
    ),
    ManualSource(
        key="jewish_wisdom",
        name="Jewish wisdom",
        default_form="concept",
        titles=(
            "Tikkun olam",
            "Tzimtzum",
            "Bashert",
            "Mensch",
            "Chutzpah",
            "Tzadik",
            "Pikuach nefesh",
            "Pilpul",
            "Devekut",
            "Kavanah",
            "Shekhinah",
            "Ein Sof",
            "Sefirot",
            "Tzedakah",
            "Mitzvah",
            "Yetzer hara",
            "Chesed",
            "Lashon hara",
            "Teshuvah",
            "Halakha",
            "Aggadah",
            "Shalom bayit",
            "Shalom",
            "Yichud",
            "Olam Haba",
        ),
    ),
    ManualSource(
        key="existentialism",
        name="Existentialist concepts",
        default_form="concept",
        titles=(
            "Bad faith (existentialism)",
            "Absurdism",
            "Authenticity (philosophy)",
            "Dasein",
            "Being-toward-death",
            "Thrownness",
            "Angst",
            "Eternal return",
            "Will to power",
            "Übermensch",
            "Ressentiment",
            "Negative capability",
            "Apollonian and Dionysian",
            "The Myth of Sisyphus",
            "Facticity",
            "Existence precedes essence",
            "Leap of faith",
            "Limit situation",
            "The Look",
            "Nihilism",
            "Master–slave morality",
            "Last man",
            "God is dead",
            "Sickness Unto Death",
        ),
    ),
    ManualSource(
        key="defense_mechanisms",
        name="Defense mechanisms",
        default_form="defense_mechanism",
        titles=(
            "Acting out",
            "Altruism",
            "Anticipation (psychology)",
            "Compartmentalization (psychology)",
            "Compensation (psychology)",
            "Conversion disorder",
            "Denial",
            "Displacement (psychology)",
            "Dissociation (psychology)",
            "Fantasy (psychology)",
            "Idealization and devaluation",
            "Identification (psychology)",
            "Intellectualization",
            "Introjection",
            "Isolation (psychology)",
            "Passive-aggressive behavior",
            "Psychological projection",
            "Projective identification",
            "Rationalization (psychology)",
            "Reaction formation",
            "Regression (psychology)",
            "Repression (psychology)",
            "Splitting (psychology)",
            "Sublimation (psychology)",
            "Thought suppression",
            "Undoing (psychology)",
            "Transference",
            "Countertransference",
            "Triangulation (psychology)",
            "DARVO",
            "Gaslighting",
            "Stonewalling",
            "Codependency",
            "Enmeshment",
            "Parentification",
            "Emotional blackmail",
            "Love bombing",
            "Hoovering (abuse)",
        ),
    ),
    ManualSource(
        key="christian_contemplative",
        name="Christian contemplative tradition",
        default_form="concept",
        titles=(
            "Lectio Divina",
            "Theosis (Eastern Christian theology)",
            "Apophatic theology",
            "Cataphatic theology",
            "Hesychasm",
            "Kenosis",
            "Imago Dei",
            "Original sin",
            "Divine grace",
            "Beatitudes",
            "Seven deadly sins",
            "Seven virtues",
            "Theological virtues",
            "Discernment of spirits",
            "The Imitation of Christ",
            "Dark Night of the Soul",
            "The Cloud of Unknowing",
            "Mystical theology",
            "Logos (Christianity)",
            "Repentance",
            "Beatific vision",
            "Examen",
            "Centering prayer",
            "Acedia",
            "Agape",
            "Sin",
            "Metanoia (theology)",
            "Sacred Heart",
            "Communion of saints",
            "Stigmata",
        ),
    ),
    ManualSource(
        key="tibetan_buddhism",
        name="Tibetan Buddhist concepts",
        default_form="concept",
        titles=(
            "Dzogchen",
            "Mahamudra",
            "Tonglen",
            "Lojong",
            "Bardo",
            "Phowa",
            "Rigpa",
            "Tibetan Buddhism",
            "Dakini",
            "Tara (Buddhism)",
            "Mandala",
            "Six Yogas of Naropa",
            "Vajra",
            "Yidam",
            "Terma (religion)",
            "Lung (Tibetan Buddhism)",
            "Ngöndro",
            "Trekchö",
            "Tögal",
            "Padmasambhava",
            "Three Vajras",
            "Sky burial",
        ),
    ),
    ManualSource(
        key="modern_wisdom",
        name="Modern wisdom and contrarian thought",
        default_form="concept",
        titles=(
            "Antifragility",
            "Skin in the Game (book)",
            "Black swan theory",
            "Lindy effect",
            "Ergodicity",
            "Hormesis",
            "Via negativa",
            "Mimetic theory",
            "Scapegoating",
            "Flow (psychology)",
            "Mindset",
            "Iatrogenesis",
            "Spontaneous order",
            "Dunbar's number",
            "Pareto principle",
            "Survivorship bias",
            "Path dependence",
            "Tragedy of the commons",
            "Schelling point",
            "Veil of ignorance",
            "The Hedgehog and the Fox",
            "Thinking, Fast and Slow",
            "Bullshit jobs",
            "Hyperreality",
            "Simulacrum",
            "Spectacle (critical theory)",
            "Liquid modernity",
            "Risk society",
            "Reflexivity (social theory)",
        ),
    ),
    ManualSource(
        key="african_philosophy",
        name="African philosophical concepts",
        default_form="concept",
        titles=(
            "Ubuntu philosophy",
            "Sankofa",
            "Maat",
            "African philosophy",
            "Negritude",
            "Ujamaa",
            "Ifá",
            "Ase (Yoruba)",
            "Communalism",
            "Pan-Africanism",
        ),
    ),
]
# Dropped (too meta / too noisy for seed scrape):
#   - "List of common misconceptions" is a meta page that only links to sub-lists
#   - "Outline of ..." pages are navigation graphs and add thousands of loosely
#     related links. Revisit in a Tier 2 pass if we want broader coverage.
